language: r
r:
  - 3.4.1
  - 3.4.2
  - 3.4.3
sudo: false
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"

repos:
  XRAN: https://xran.yihui.name

before_install:
  - "curl https://xran.yihui.name/.gitconfig -o ~/.gitconfig"

after_success:
  - "(curl https://xran.yihui.name/r-xran | bash)"
